<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GameDir Condition="'$(GameDir)' == ''">$(MSBuildThisFileDirectory)..\..\..\..\..</GameDir>
    <OutputPath>..\Assemblies</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup><Reference Include="UnityEngine.IMGUIModule"><HintPath>$(GameDir)\RimWorldWin64_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="com.rlabrecque.steamworks.net"><HintPath>$(GameDir)\RimWorldWin64_Data\Managed\com.rlabrecque.steamworks.net.dll</HintPath><Private>false</Private></Reference>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameDir)\RimWorldWin64_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="netstandard">
      <HintPath>$(GameDir)\RimWorldWin64_Data\Managed\netstandard.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameDir)\RimWorldWin64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(GameDir)\..\..\workshop\content\294100\2009463077\Current\Assemblies\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SeamlessAncientBunkers">
      <HintPath>$(MSBuildThisFileDirectory)..\..\..\1.6\Assemblies\SeamlessAncientBunkers.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>



