using System;
using System.Linq;
using HarmonyLib;
using RimWorld;
using SeamlessAncientBunkers;
using UnityEngine;
using Verse;
using Verse.AI;

namespace SABTransitTests
{
 public class TransitProbe : GameComponent
 {
  string lastState; int stage,started,logged; Pawn worker,patient,slave,mech; AncientHatch hatch; Building_Bed bed; Building_MechCharger charger; Thing battery; float initialEnergy; IntVec3 endCell;
  public TransitProbe(Game game){}
  public override void ExposeData(){Scribe_Values.Look(ref stage,"transitStage");Scribe_Values.Look(ref started,"transitStarted");Scribe_References.Look(ref worker,"transitWorker");Scribe_References.Look(ref patient,"transitPatient");Scribe_References.Look(ref slave,"transitSlave");Scribe_References.Look(ref mech,"transitMech");Scribe_References.Look(ref hatch,"transitHatch");Scribe_References.Look(ref bed,"transitBed");Scribe_Values.Look(ref endCell,"transitEndCell");}
  void Check(bool ok,string label){if(!ok)throw new Exception(label);Log.Message("[SAB TRANSIT] PASS "+label);}
  IntVec3 Cell(Map m)=>CellFinder.StandableCellNear(m==hatch.Map?hatch.Position:hatch.exit.Position,m,7);
  Pawn Pawn(Map m){Pawn p;do{p=PawnGenerator.GeneratePawn(new PawnGenerationRequest(PawnKindDefOf.Colonist,Faction.OfPlayer,forceGenerateNewPawn:true,canGeneratePawnRelations:false));}while(p.WorkTypeIsDisabled(WorkTypeDefOf.Hauling));foreach(var t in p.story.traits.allTraits.ToList())p.story.traits.RemoveTrait(t);GenSpawn.Spawn(p,Cell(m),m);p.workSettings.EnableAndInitialize();foreach(var d in DefDatabase<WorkTypeDef>.AllDefsListForReading)if(!p.WorkTypeIsDisabled(d))p.workSettings.SetPriority(d,0);return p;}
  void Move(Pawn p,Map m){p.jobs.StopAll();if(p.Spawned)p.DeSpawn();GenSpawn.Spawn(p,Cell(m),m);}
  Building_Bed Bed(Map m){var b=(Building_Bed)ThingMaker.MakeThing(ThingDefOf.Bed,ThingDefOf.WoodLog);b.SetFaction(Faction.OfPlayer);var c=GenRadial.RadialCellsAround(m==hatch.Map?hatch.Position:hatch.exit.Position,12,true).First(x=>x.InBounds(m)&&x.Standable(m)&&x.GetEdifice(m)==null&&!x.Fogged(m)&&GenAdj.OccupiedRect(x,Rot4.North,b.def.size).All(z=>z.InBounds(m)&&z.Standable(m)&&z.GetEdifice(m)==null));GenSpawn.Spawn(b,c,m);b.Medical=true;b.SetForbidden(false,false);return b;}
    Thing Building(string name,Map map,IntVec3? at=null){var d=ThingDef.Named(name);var t=ThingMaker.MakeThing(d,d.MadeFromStuff?ThingDefOf.Steel:null);t.SetFaction(Faction.OfPlayer);var c=at??GenRadial.RadialCellsAround(map==hatch.Map?hatch.Position:hatch.exit.Position,15,true).First(x=>GenAdj.OccupiedRect(x,Rot4.North,d.size).ExpandedBy(1).All(z=>z.InBounds(map)&&z.Standable(map)&&z.GetEdifice(map)==null&&!z.Fogged(map)));return GenSpawn.Spawn(t,c,map);}
  void BeginRescue(Map source,Map destination){Move(worker,destination);if(patient==null)patient=Pawn(source);else Move(patient,source);patient.health.AddHediff(HediffDefOf.Anesthetic).Severity=1f;Check(patient.Downed,"patient is actually incapacitated");if(bed!=null)bed.Destroy();bed=Bed(destination);var native=JobMaker.MakeJob(JobDefOf.Rescue,patient,bed);native.count=1;bed.SetFaction(Faction.OfAncients);Check(PawnTransit.Plan(worker,patient,bed,native)==null,"foreign destination bed rejected");bed.SetFaction(Faction.OfPlayer);hatch.SetForbidden(true,false);Check(PawnTransit.Plan(worker,patient,bed,native)==null,"forbidden hatch rejected");hatch.SetForbidden(false,false);var job=PawnTransit.Plan(worker,patient,bed,native);Check(job!=null,"three-map-target rescue planned without moving real pawns");Check(worker.Map==destination&&patient.Map==source&&!RemotePawnScope.Active,"rescue planning restores map/position context");Check(worker.jobs.TryTakeOrderedJob(job),"carrier accepts pickup journey");started=Manager.Now;}
  public override void GameComponentTick()
  {
   if(!GenCommandLine.CommandLineArgPassed("sab-transit-tests")||Current.ProgramState!=ProgramState.Playing||LongEventHandler.AnyEventNowOrWaiting||stage==99)return;
   Application.runInBackground=true;foreach(var w in Find.WindowStack.Windows.ToList())if(w.forcePause)Find.WindowStack.TryRemove(w,false);
   try{
    Find.TickManager.CurTimeSpeed=TimeSpeed.Superfast;
    if(stage==0){hatch=Find.Maps.SelectMany(m=>m.listerThings.AllThings.OfType<AncientHatch>()).First(h=>Portal.Other(h)!=null);Manager.Current.Cleanup();BunkerMod.Settings.enabled=true;BunkerMod.Settings.work=true;BunkerMod.Settings.haul=true;BunkerMod.Settings.debug=true;BunkerMod.Settings.scanInterval=120;foreach(var m in new[]{hatch.Map,hatch.PocketMap}){foreach(var p in m.mapPawns.AllPawnsSpawned.ToList())p.Destroy();foreach(var b in m.listerThings.AllThings.OfType<Building_Bed>().ToList())b.Destroy();}Manager.Current.EnableClearedBunkers();worker=Pawn(hatch.Map);BeginRescue(hatch.PocketMap,hatch.Map);stage=1;}
    foreach(var p in new[]{worker,patient,slave})if(p!=null&&!p.Dead){if(p.needs.food!=null)p.needs.food.CurLevelPercentage=1;if(p.needs.rest!=null)p.needs.rest.CurLevelPercentage=1;if(p.needs.mood!=null)p.needs.mood.CurLevelPercentage=1;}
    var state=worker.CurJobDef+":"+Broker.For(worker)?.purpose+":"+Broker.For(worker)?.carrying+":"+worker.carryTracker.CarriedThing+":"+worker.Map+":"+patient.MapHeld; if(lastState!=state){lastState=state;Log.Message("[SAB TRANSIT] STATE "+state); }
    if(stage==1&&worker.carryTracker.CarriedThing==patient&&Broker.For(worker)?.carrying==true){Check(true,"living patient picked up for physical cross-level rescue");stage=2;GameDataSaveLoader.SaveGame("SAB-TransitCheckpoint");Log.Message("[SAB TRANSIT] RELOAD REQUIRED");Application.Quit();stage=99;return;}
    if(stage==2){Check(worker.carryTracker.CarriedThing==patient&&Broker.For(worker)?.deliveryTarget==bed,"passenger identity and destination survive fresh-process reload");stage=3;}
    if(stage==3&&patient.InBed()&&patient.CurrentBed()==bed){Check(patient.Map==hatch.Map,"patient delivered from bunker into surface bed");BeginRescue(hatch.Map,hatch.PocketMap);stage=4;}
    if(stage==4&&patient.InBed()&&patient.CurrentBed()==bed){Check(patient.Map==hatch.PocketMap,"patient delivered from surface into bunker bed");Check(Find.Maps.SelectMany(m=>m.mapPawns.AllPawns).Count(p=>p==patient)==1,"exactly one patient after repeated carrying");slave=Pawn(hatch.Map);slave.guest.SetGuestStatus(Faction.OfPlayer,GuestStatus.Slave);Check(slave.IsSlaveOfColony&&Portal.Eligible(slave),"colony slave is eligible under native slave status");var route=Graph.Reachable(slave).First(r=>r.map==hatch.PocketMap);var job=Broker.Begin(slave,route,Purpose.Manual);Check(job!=null&&slave.jobs.TryTakeOrderedJob(job),"slave starts permitted cross-level trip");stage=5;started=Manager.Now;}
    if(stage==5&&slave.Map==hatch.PocketMap&&Broker.For(slave)==null){Check(slave.IsSlaveOfColony,"slave status survives completed transfer");Move(worker,hatch.Map);endCell=Cell(hatch.Map);Check(LinkedOrders.Issue(worker,JobMaker.MakeJob(JobDefOf.Goto,Cell(hatch.PocketMap)),hatch.PocketMap,queue:false),"first remote order accepted");Check(LinkedOrders.Issue(worker,JobMaker.MakeJob(JobDefOf.Goto,endCell),hatch.Map,queue:true),"return order added to saved cross-map queue");Check(Manager.Current.queuedOrders.Count(q=>q.pawn==worker)==1,"queued order retains source-map destination");stage=6;started=Manager.Now;}
    if(stage==6&&worker.Map==hatch.Map&&worker.Position==endCell&&Broker.For(worker)==null&&Manager.Current.queuedOrders.All(q=>q.pawn!=worker)){Check(true,"queued round trip completes on correct maps");mech=PawnGenerator.GeneratePawn(PawnKindDef.Named("Mech_Lifter"),Faction.OfPlayer);GenSpawn.Spawn(mech,Cell(hatch.PocketMap),hatch.PocketMap);worker.health.AddHediff(HediffDef.Named("MechlinkImplant"),worker.health.hediffSet.GetBrain());mech.relations.AddDirectRelation(PawnRelationDefOf.Overseer,worker);Check(Portal.Eligible(mech)&&Graph.Reachable(mech).Any(r=>r.map==hatch.Map),"controlled Biotech mech can route to other map");Check(!RemotePawnScope.Active,"no leaked remote probe contexts");charger=(Building_MechCharger)Building("BasicRecharger",hatch.Map);battery=Building("Battery",hatch.Map,charger.Position+IntVec3.East*3);for(int x=0;x<=3;x++)Building("PowerConduit",hatch.Map,charger.Position+IntVec3.East*x);hatch.Map.powerNetManager.UpdatePowerNetsAndConnections_First();battery.TryGetComp<CompPowerBattery>().AddEnergy(400);charger.Power.PowerOn=true;mech.needs.energy.CurLevel=10;initialEnergy=mech.needs.energy.CurLevel;Check(charger.CanPawnChargeCurrently(mech),"powered charger can accept mech");var charging=MechTransit.Charge(mech,new JobGiver_GetEnergy_Charger{forced=true});Check(charging!=null&&mech.jobs.TryTakeOrderedJob(charging),"mech starts remote autonomous recharge route");stage=7;started=Manager.Now;}
    if(stage==7){battery.TryGetComp<CompPowerBattery>().AddEnergy(400);charger.Power.PowerOn=true;if(mech.Map==charger.Map&&mech.CurJobDef==JobDefOf.MechCharge&&mech.needs.energy.CurLevel>initialEnergy+0.05f){Check(true,"mech physically reaches remote charger and gains energy");stage=99;Log.Message("[SAB TRANSIT] ACCEPTANCE COMPLETE");Application.Quit();}}
    if(stage!=99&&Manager.Now>=logged){logged=Manager.Now+1200;Log.Message("[SAB TRANSIT] progress stage="+stage+" job="+worker.CurJob+" intent="+Broker.For(worker)?.purpose+" carry="+worker.carryTracker.CarriedThing+" map="+worker.Map+" patient="+patient.CurJob);}
    if(stage!=99&&Manager.Now-started>16000)throw new Exception("Timeout stage="+stage+" job="+worker.CurJob+" intent="+Broker.For(worker)?.purpose);
   }catch(Exception e){stage=99;Log.Error("[SAB TRANSIT] FAIL "+e);Application.Quit();}
  }
 }
}

